CordEstates/Controllers/EventController.cs
using AutoMapper;
using CordEstates.Helpers;
using CordEstates.Models.DTOs;
using CordEstates.Wrappers.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CordEstates.Controllers
{
    public class EventController : Controller
    {

        readonly IMapper _mapper;
        readonly ILoggerManager _logger;
        readonly IRepositoryWrapper _repositoryWrapper;
        public EventController(ILoggerManager logger, IRepositoryWrapper repositoryWrapper, IMapper mapper)
        {

            _logger = logger;
            _repositoryWrapper = repositoryWrapper;
            _mapper = mapper;

        }

        // GET: Event
        public async Task<IActionResult> Index()
        {
            //todo - possible enable customer to register interest.
            List<EventDTO> events = new List<EventDTO>();

            try
            {
                events = _mapper.Map<List<EventDTO>>(await _repositoryWrapper.Event.GetAllEventsAsync());
                return View(nameof(Index), events);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Problem occurred retrieving events: {ex}");
                throw new Exception($"Problem occurred retrieving events: {ex}");
            }
        }


    }
}

CordEstates/Controllers/InterestedPropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CordEstates.Areas.Identity.Data;
using CordEstates.Models.DTOs;
using CordEstates.Helpers;
using CordEstates.Wrappers.Interfaces;
using AutoMapper;
using CordEstates.Entities;

namespace CordEstates.Controllers
{
    public class InterestedPropertyController : Controller
    {
        private readonly ILoggerManager _logger;
        readonly IMapper _mapper;
        readonly IRepositoryWrapper _repositoryWrapper;

        public InterestedPropertyController(ILoggerManager logger, IMapper mapper, IRepositoryWrapper repositoryWrapper)
        {
            _repositoryWrapper = repositoryWrapper;
            _mapper = mapper;
            _logger = logger;

        }

        // GET: InterestedProperty
        public async Task<IActionResult> Index()
        {
            string user = await _repositoryWrapper.Employee.GetUserId(User);
            var customer = await _repositoryWrapper.Customer.GetCustomerByUserId(user);
            CustomerListingDTO customerListing = _mapper.Map<CustomerListingDTO>(await _repositoryWrapper.Customer.GetCustomersPropertyAsync(customer.Id));
            return View(nameof(Index),customerListing);
            //todo change what the index is displaying
            //todo redirect the details page to the listing controller details
        }
               

    

    
    }
}

CordEstates/Controllers/ListingController.cs
using AutoMapper;
using CordEstates.Entities;
using CordEstates.Helpers;
using CordEstates.Models;
using CordEstates.Models.DTOs;
using CordEstates.Wrappers.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace CordEstates.Controllers
{
    public class ListingController : Controller
    {



        readonly IMapper _mapper;
        readonly IRepositoryWrapper _repositoryWrapper;
        readonly ILoggerManager _logger;
        public ListingController(ILoggerManager logger
            , IRepositoryWrapper repositoryWrapper, IMapper mapper)
        {
            _logger = logger;
            _repositoryWrapper = repositoryWrapper;
            _mapper = mapper;

        }

        // GET: Listing
        public async Task<IActionResult> Index(int pageNumber =1)
        {
            try
            {
                var data = _mapper.Map<List<ExtendedListingDTO>>(await _repositoryWrapper.Listing.GetAllListingsForSaleAsync());
                IQueryable<ExtendedListingDTO> dataQuerable = data.AsQueryable();
                var model = PaginatedList<ExtendedListingDTO>.Create(dataQuerable, pageNumber, 5);
                return View(nameof(Index), model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Unable to retrieve the Listings: {ex}");
                throw new Exception($"Unable to retrieve the Listings: {ex}");
            }
        }




        //// GET: Listing/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    ListingDetailDTO listing = new ListingDetailDTO();
        //    try
        //    {
        //        listing = _mapper.Map<ListingDetailDTO>(await _repositoryWrapper.Listing.GetListingByIdAsync(id));

        //    }
        //    catch (Exception ex)
        //    {
        //        _logger.LogError($"Unable to retrieve the Listing with id-{id} : {ex}");
        //        throw new Exception($"Unable to retrieve the Listing with id-{id}: {ex}");
        //    }


        //    if (listing == null)
        //    {
        //        return NotFound();
        //    }
        //    listing.Listing = _mapper.Map<Listing>(listing);
        //    return View(listing);
        //}
        //// GET: Admin/Listing/Edit/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ListingDetailDTO listing = new ListingDetailDTO();
            try
            {
                listing = _mapper.Map<ListingDetailDTO>(await _repositoryWrapper.Listing.GetListingByIdAsync(id));

            }
            catch (Exception ex)
            {
                _logger.LogError($"Unable to retrieve the Listing with id-{id} : {ex}");
                throw new Exception($"Unable to retrieve the Listing with id-{id}: {ex}");
            }


            if (listing == null)
            {
                return NotFound();
            }

            if(User.IsInRole("Customer"))
            {
                string user = await _repositoryWrapper.Employee.GetUserId(User);
                var cust = await _repositoryWrapper.Customer.GetCustomerByUserId(user);

                var props = await _repositoryWrapper.Customer.GetCustomersPropertyAsync(cust.Id);
                var r = props.PropertiesInterestedIn
                    .Where(x => x.CustomerId.Equals(cust.Id) && x.PropertyId.Equals(listing.Id)).FirstOrDefault();
                if (r == null )
                {
                    ViewData["following"] = false;
                }
                else
                {
                    ViewData["following"] = true;
                }
           


            }
            return View(nameof(Details), listing);
        }

        // POST: Admin/Listing/Edit/5
        // To protect from over posting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ListingDetailDTO listingDetailDTO,bool follow)
        {
            if (id != listingDetailDTO.Id)

            {
                _logger.LogError($"Id did not match for to {nameof(Edit)}.  Expected:{id}, Actual{listingDetailDTO.Id}");
                return RedirectToAction(nameof(Index));
            }


            if (ModelState.IsValid)
            {
                try
                {
                    var mapped = _mapper.Map<Listing>(listingDetailDTO);
                    
                   var listing = await _repositoryWrapper.Listing.GetListingByIdAsync(id);
                    string user = await _repositoryWrapper.Employee.GetUserId(User);
                    await _repositoryWrapper.Customer.ToggleFollow(user, listing,follow);


                 

                    await _repositoryWrapper.SaveAsync();

                }
                catch (Exception ex)
                {

                    _logger.LogError($"Error updating listing: {ex}");


                }
                return RedirectToAction(nameof(Index));
            }
           return View(nameof(Details), listingDetailDTO);
        }
      



    }
}

CordEstates/Controllers/ServiceController.cs
using AutoMapper;
using CordEstates.Helpers;
using CordEstates.Models.DTOs;
using CordEstates.Wrappers.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CordEstates.Controllers
{
    public class ServiceController : Controller
    {


        readonly IMapper _mapper;
        readonly IRepositoryWrapper _repositoryWrapper;
        readonly ILoggerManager _logger;
        public ServiceController(ILoggerManager logger, IMapper mapper, IRepositoryWrapper repositoryWrapper)
        {
            _logger = logger;
            _repositoryWrapper = repositoryWrapper;
            _mapper = mapper;

        }

        // GET: Services
        public async Task<IActionResult> Index()
        {
            var services = new List<ServiceDTO>();
            try
            {
                services = _mapper.Map<List<ServiceDTO>>(await _repositoryWrapper.Service.GetAllServicesAsync());
                return View(nameof(Index), services);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Problem has occurred on loading services: {ex}");
                throw new Exception($"problem has occured loading services {ex}");
            }



        }
    }
}

CordEstates/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CordEstates</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 
    <link href="~/css/modern-business.css" rel="stylesheet" />
   


</head>
<body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">CordEstates</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Listing" asp-action="Index">Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Service" asp-action="Index">Services</a>
                    </li>

                    @{
                        if (User.IsInRole("Staff"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Staff" asp-controller="AgentDashboard" asp-action="Index">Dashboard</a>
                            </li>
                        }
                        else if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Staff" asp-controller="AdminDashboard" asp-action="Index">Dashboard</a>
                            </li>
                        }
                        else if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="InterestedProperty" asp-action="Index">My Properties</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact us</a>
                            </li>
                        }
                    }


                </ul>
            </div>
        </div>
    </nav>

    @RenderSection("Header", false)

    <div class="container">
        <main role="main" class="pb-3 ">
            @RenderBody()
        </main>
    </div>

    <footer class=" bg-dark border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CordEstates - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>